[FEATURE] Add Dzongkha
radar/distance_of_time_in_words pull request #134
Opened 2024-09-19 07:52 UTC by KinWang-2013

This PR adds support for Dzongkha which is the national language of Bhutan 🇧🇹

2024-09-19 07:56 UTC, KinWang-2013 commented
@radar please check this

2024-09-19 08:20 UTC, dblock requested changes
Looks good! Can we add some more tests than just for 1 second, please?

I know it's unrelated, but we do need to fix CI. If you could please help out do the upgrades, we can probably drop 2.4 and add 3.2 and 3.1 (separate PR would be great).

2024-09-19 08:56 UTC, KinWang-2013 commented
> Looks good! Can we add some more tests than just for 1 second, please?
> 
> I know it's unrelated, but we do need to fix CI. If you could please help out do the upgrades, we can probably drop 2.4 and add 3.2 and 3.1 (separate PR would be great).

sure, I will

2024-09-19 12:15 UTC, KinWang-2013 commented
@dblock added some more tests, I will try doing upgrades in another PR

2024-09-24 05:19 UTC, KinWang-2013 commented
> @dblock added some more tests, I will try doing upgrades in another PR

@dblock please check, the other PR is #135

2024-09-27 10:52 UTC, dblock commented
CI should pass now after #135, rebase?

2024-09-27 13:29 UTC, dblock requested changes
Nit, missing a period in CHANGELOG, sorry!

2024-09-27 13:29 UTC, dblock commented on CHANGELOG.md
> +* [#134](https://github.com/radar/distance_of_time_in_words/pull/134): Add support for Dzongkha language (National language of Bhutan) - [@KinWang-2013](https://github.com/KinWang-2013)
```suggestion
* [#134](https://github.com/radar/distance_of_time_in_words/pull/134): Add support for Dzongkha, the National language of Bhutan - [@KinWang-2013](https://github.com/KinWang-2013).
```

2024-09-27 13:32 UTC, KinWang-2013 commented
> Nit, missing a period in CHANGELOG, sorry!

updated, thanks

2024-09-27 18:40 UTC, dblock approved these changes

2024-09-27 18:40 UTC, merged